- name: Install nginx
  hosts: websever
  become: true

  - name: Install nginx
    yum:
      name: nginx
      state: present

  - name: Insert Index Page
    template:
      src: index.html
      dest: /etc/ansible/index.html

  - name: Start NGiNX
    service:
      name: nginx
      state: started